### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by abhimanyusinghgaur** [shashank-iitj/pushowl-notification-widget#4]
In mobile view I have introduced some margin between the widget  border and screen border.
Should it be kept or the widget border touches the screen border?

**Comment by shashank-iitj** [comment]
![mobile](https://cloud.githubusercontent.com/assets/794576/23094018/6d064934-f617-11e6-9fc5-1b21334c3e60.png)

There would be no margin in the mobile view.

**Comment by shashank-iitj** [comment]
![mobile](https://cloud.githubusercontent.com/assets/794576/23094044/a54a0556-f617-11e6-982a-a18d0b0fc4bd.png)

The previous comment didn't give the actual idea because of white background. Check this one.

**Comment by abhimanyusinghgaur** [comment]
Resolved in #6.
